server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:orderdb}
    username: ${DB_USER:benchmark}
    password: ${DB_PASSWORD:benchmark}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: WARN
    com.github.Bahaaio: INFO
